sudo: false
language: node_js
node_js:
  - stable
  - 12
  - 11
  - 10
  - 9
  - 8
  - 6
notifications:
  email: false
after_success:
  - npm install -g codecov
  - npm run test:ci > coverage.lcov && codecov
